GET http://127.0.0.1:8000/api/v1/categories
Authorization: Basic Eve Pass4Eve!
Content-Type: application/json


###
#GET http://127.0.0.1:8000/api/v1/expenses?limit=12&offset=0
#GET http://127.0.0.1:8000/api/v1/expenses
GET http://127.0.0.1:8000/api/v1/expenses?limit=2&offset=0
Authorization: Basic Eve Pass4Eve!
Content-Type: application/json


###
GET http://127.0.0.1:8000/api/v1/expenses?limit=12&offset=1
Authorization: Basic Adam Pass4Adam!
Content-Type: application/jso

###
GET http://127.0.0.1:8000/api/v1/expenses
Authorization: Basic Adam Pass4Adam!
Content-Type: application/js

###
GET http://127.0.0.1:8000/api/v1/expenses?category__name=g
Authorization: Basic Adam Pass4Adam!


###
GET http://127.0.0.1:8000/api/v1/expenses?cost_max=1000&cost_min=75&date_after=2020-09-25&date_before=2020-09-28&name=e&offset=0
Authorization: Basic Adam Pass4Adam!


###
GET http://127.0.0.1:8000/api/v1/me
Authorization: Basic Adam Pass4Adam!

###
GET http://127.0.0.1:8000/api/v1/me
Authorization: Basic Eve Pass4Eve!


###
GET http://127.0.0.1:8000/api/v1/me
Authorization: Basic eve Pass4eve!

###
POST http://127.0.0.1:8000/api/v1/expense/new
Authorization: Basic Adam Pass4Adam!
Content-Type: application/json

    {
      "name": "Purchase of Personal - ADAM#3",
      "cost": "999.00",
      "date": "2020-11-01",
      "owner": 2,
      "category": 103 
    }

###
GET http://127.0.0.1:8000/api/v1/expenses?name=Adam
Authorization: Basic Adam Pass4Adam!


###
DELETE http://127.0.0.1:8000/api/v1/expense/1217
Authorization: Basic Adam Pass4Adam!


###
PUT http://127.0.0.1:8000/api/v1/expense/1216
Authorization: Basic Adam Pass4Adam!
Content-Type: application/json

    {
      "name": "APurchase of Personal - ADAM#23",
      "cost": "2909.00",
      "date": "2020-12-01",
      "owner": 2,
      "category": 62
    }

###
GET http://127.0.0.1:8000/api/v1/expense/1216
Authorization: Basic Adam Pass4Adam!
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/v1/stats?category__name=Clo
Authorization: Basic Adam Pass4Adam!

###
GET http://127.0.0.1:8000/api/v1/expenses?name=Savings&cost_max=600&cost_min=500
Authorization: Basic Eve Pass4Eve!


###
GET http://127.0.0.1:8000/api/v1/expenses?limit=20&offset=0&cost_min=50&cost_max=150&date_before=2020-10-15&name=F&category__name=R
Authorization: Basic Eve Pass4Eve!


### 2604
DELETE http://127.0.0.1:8000/api/v1/expense/2604
Authorization: Basic Eve Pass4Eve!