GET http://127.0.0.1:8000/api/v1/categories
Authorization: Basic Eve Pass4Eve!
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/v1/users
Authorization: Basic Eve Pass4Eve!
Content-Type: application/json


###
#GET http://127.0.0.1:8000/api/v1/expenses
GET http://127.0.0.1:8000/api/v1/expenses?limit=12&offset=0
Authorization: Basic Eve Pass4Eve!
Content-Type: application/json


###
GET http://127.0.0.1:8000/api/v1/expenses?limit=12&offset=1
Authorization: Basic Adam Pass4Adam!
Content-Type: application/jso

###
GET http://127.0.0.1:8000/api/v1/expenses
Authorization: Basic Adam Pass4Adam!
Content-Type: application/js

###
GET http://127.0.0.1:8000/api/v1/expenses?category__name=g
Authorization: Basic Adam Pass4Adam!


###
GET http://127.0.0.1:8000/api/v1/expenses?cost_max=1000&cost_min=75&date_after=2020-09-25&date_before=2020-09-28&name=e&offset=0
Authorization: Basic Adam Pass4Adam!


###
GET http://127.0.0.1:8000/api/v1/me
Authorization: Basic Adam Pass4Adam!

###
GET http://127.0.0.1:8000/api/v1/me
Authorization: Basic Eve Pass4Eve!


###
GET http://127.0.0.1:8000/api/v1/me
Authorization: Basic eve Pass4eve!