# Generated by Django 3.1.1 on 2020-10-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
